services:
  - type: web
    name: telemetry-api
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:10000
      - key: ApplicationInsights__ConnectionString
        sync: false
    healthCheckPath: /swagger
    plan: free

